version: "3.8"

services:
  database:
    container_name: postgres
    image: postgres:alpine
    restart: always
    networks:
      - auth
    environment:
      - POSTGRES_USER=pgAdmin
      - POSTGRES_PASSWORD=crazyPass123
      - POSTGRES_DB=authenticator
    ports:
      - 5432:5432
    #volumes:
    #  - db:/var/lib/postgresql/data 
networks:
  auth:

#volumes:
#  db:
